sudo: false
language: node_js
node_js:
  - "stable"
  - "0.12"
  - "0.10"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
  node_js: "stable"
    before_install:
      - npm install -g npm@next
